blank_issues_enabled: true
contact_links:
  - name: Documentation issue
    url: https://github.com/MicrosoftDocs/edge-developer/issues
    about: Report issues related to the documentation of DevTools here.
